### ISSUE TITLE
Sentiment analysis with qdap

### ISSUE THREAD

**Issue by stripathi08** [trinker/qdap#209]
Using sentiment_frame only uses the frame and not qdap dictionaries.
Is their a way i can use both my words with the set inbuilt package's words? 
For example - 
'> corpus<- "He is a liar."
> frame<- sentiment_frame("liar","hater",pos.weights=1, neg.weights=-1)
> z<- counts(polarity(corpus, polarity.frame=frame))
> z
  all wc polarity pos.words neg.words      text.var
1 all  4      0.5      liar         - He is a liar.
> corpus<- "He is a good liar."
> frame<- sentiment_frame("liar","hater",pos.weights=1, neg.weights=-1)
> z<- counts(polarity(corpus, polarity.frame=frame))
> z
  all wc polarity pos.words neg.words           text.var
1 all  5    0.447      liar         - He is a good liar.'
Also, why is the polarity decreasing?

**Comment by trinker** [comment]
You seem to have opened the same question twice:https://github.com/trinker/qdap/issues/208

Closing please reopen if I'm incorrect.
