### ISSUE TITLE
qdap install 64-bit Mac

### ISSUE THREAD

**Issue by ghost321** [trinker/qdap#216]
![screen shot 2015-10-06 at 3 28 48 pm](https://cloud.githubusercontent.com/assets/7201010/10321554/fe1f6dba-6c3e-11e5-9fa4-093cd4bcd011.png)
I'm trying to install 'qdap' and 'qdapTools' in R and this is the message I get:

> library(qdapTools)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘data.table’ 1.9.4 is already loaded, but >= 1.9.6 is required
Error: package or namespace load failed for ‘qdapTools’

I do that latest version of data.table installed though..Wondering why error

**Comment by trinker** [comment]
There has been a 1.96 release of **data.table** for a month or so:  https://cran.r-project.org/web/packages/data.table/index.html

This fixes solaris errors in **qdapTools**

**Comment by ghost321** [comment]
I do have the 1.96 version of data.table

**Comment by trinker** [comment]
This line indicates you do not:

```
namespace ‘data.table’ 1.9.4 is already loaded, but >= 1.9.6 is required
```

**Comment by ghost321** [comment]
Please refer to the session_info() image I added to the post
![screen shot 2015-10-06 at 3 28 48 pm](https://cloud.githubusercontent.com/assets/7201010/10321699/b5a238b4-6c3f-11e5-97c0-22a09827343b.png)

**Comment by trinker** [comment]
Can you start a new session and run:

```r
if (!require("pacman")) install.packages("pacman")
pacman::p_ver(data.table)
```

**Comment by trinker** [comment]
I believe you installed **data.table** (1.96) after you already loaded it (1.94) and then installed **qdap** in the same session but do not have the information from you that is necessary to confirm this hypothesis.  The original 1.94 is already in namespace.  

Without doing what I've asked above it is impossible to diagnose this problem.  The information you gave is not helpful to further understanding the problem, it merely documents what you're saying.  Restarting R in a clean vanilla session and running `utils::packageVersion("data.table")` would give me new, useful information to diagnose.

**Comment by trinker** [comment]
I will assume the problem was as I mentioned above and am closing this.  Feel free to reopen if is not solved.
