### ISSUE TITLE
ignore.case = FALSE does not work

### ISSUE THREAD

**Issue by karilint** [trinker/qdap#225]
Example:
```
x <- c("Mr. Jones is here at 7:30 p.m.",  
       "Check it out at www.github.com/trinker/qdap",
       "i.e. He's a sr. dr.; the best in 2012 A.D.",
       "the robot at t.s. is 10ft. 3in.")

replace_abbreviation(x, ignore.case = FALSE)
```
`Error in nchar(pattern) : 'nchar()' requires a character vector`

My R version (Windows 10) is 3.3.2 (2016-10-31) and I have updated all packages. Any idea why I get this error message?
-Kari

**Comment by trinker** [comment]
Thanks for the catch should be fixed in the dev version:

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh(
    "trinker/qdapDictionaries",
    "trinker/qdapRegex",
    "trinker/qdapTools",
    "trinker/qdap"
)
```

**Comment by karilint** [comment]
Great!
I'll load the update as soon as it is officially available.
-Kari
