### ISSUE TITLE
Error during installation in qdap package.How to Resolve  it?

### ISSUE THREAD

**Issue by ashokdv** [trinker/qdap#243]
package or namespace load failed for 'qdap':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/ASHOK SAI/Documents/R/win-library/3.4/qdap'
In R CMD INSTALL

**Comment by cokelly** [comment]
If it's any help, Java installs are notoriously fiddly and so uninstalling and reinstalling Java, rJava, qdap etc (deleting the R packages from the directory) might help. Beyond that I've just had the same experience with updating qdap and so didn't have it compile the x86 version:

`install.packages("qdap", INSTALL_opts = "--no-multiarch")`

**Comment by ashokdv** [comment]
Thanks.Error resolved.

**Comment by prat280** [comment]
This was very helpful. I was stuck on a code failing to install the qdap package. thanks a lot
